name: tests

on:
  workflow_call:
    inputs:
      node-versions:
        description: 'JSON array of node versions to test'
        required: false
        type: string
        default: '["20.x", "22.x", "24.x"]'
      lint:
        description: 'Run npm run lint'
        required: false
        type: boolean
        default: true
      build:
        description: 'Run npm run build before lint/test'
        required: false
        type: boolean
        default: false

jobs:
  test:
    strategy:
      matrix:
        node-version: ${{ fromJson(inputs.node-versions) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          # cache: "npm" # needs lockfile if enabled

      - run: npm install
      - if: ${{ inputs.build }}
        run: npm run build
      - if: ${{ inputs.lint }}
        run: npm run lint
      - run: npm test
